apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: larry
spec:
  volumes:
  - name: moe
    secret:
      secretName: moe
  containers:
  - name: busybox
    image: busybox:1.33.1
    command: ['sh', '-c', 'cat /etc/credentials/username; cat /etc/credentials/password; while true; do sleep 5; done']
    volumeMounts:
      - name: moe
        readOnly: true
        mountPath: "/etc/credentials"


        aws-cfn-bootstrap-py3-latest.tar.gz  password.txt  secret-pod.yml  username.txt
cloud_user@k8s-cli:~$ vi secret-pod.yml
cloud_user@k8s-cli:~$ k create -f secret-pod.yml
pod/secret-pod created
cloud_user@k8s-cli:~$ k get pod -n larry
NAME         READY   STATUS    RESTARTS   AGE
secret-pod   1/1     Running   0          15s
cloud_user@k8s-cli:~$ k exec -n larry secret-pod -it -- sh
/ # env
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://10.96.0.1:443
HOSTNAME=secret-pod
SHLVL=1
HOME=/root
TERM=xterm
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
KUBERNETES_SERVICE_HOST=10.96.0.1
PWD=/
/ # cd /etc/credentials/
/etc/credentials # ls
password  username
/etc/credentials # cat username
/etc/credentials # cat password
QTgzTWFlS296Cg==/etc/credentials #